### ISSUE TITLE
s fc-component deploy --help 会执行 pre Hook 内容

### ISSUE THREAD

**Issue by git-qfzhang** [Serverless-Devs-Awesome/fc-alibaba-component#78]
## 现象

当 template.yaml 中存在 pre Hook 操作时，执行 `s fc-component deploy --help` 也会执行 pre Hook 中的操作，例如我有如下 yaml 文件：

```yaml
CustomGolangComponent:
  Component: fc
  Provider: alibaba
  Extends:
    deploy:
      - Hook: make build
        Path: ./
        Pre: true
  Properties:
    Region: 'cn-hangzhou'
    Detail:
      Service:
        Name: custom-runtime-demo
      Function:
        Name: custom-golang
        CodeUri:
          Uri: ./code
          Excludes:
            - build-image
            - .env
            - evt
            - code/main.go
            - template.yml
            - .s
        CAPort: 8080
        Handler: main.handler
        MemorySize: 512
        Runtime: custom
```

则执行  `s CustomGolangComponent deploy --help` 时也会执行 `Hook` 中的指令。

![image](https://user-images.githubusercontent.com/52195264/101170306-3b5faa00-3679-11eb-8a72-e06f84e7c01c.png)
