### ISSUE TITLE
s invoke docker 错误

### ISSUE THREAD

**Issue by git-qfzhang** [Serverless-Devs-Awesome/fc-alibaba-component#79]
## 复现

当项目 `codeUri` 包含 `Src` 字段时，使用 `s invoke docker` 会报错，示例 yaml 文件如下所示：

```yaml
CustomGolangComponent:
  Component: fc
  Provider: alibaba
  Extends:
    deploy:
      - Hook: make build
        Path: ./
        Pre: true
  Properties:
    Region: 'cn-hangzhou'
    Service:
      Name: custom-runtime-demo
    Function:
      Name: custom-golang
      CodeUri:
        Src: ./code
        Excludes:
          - build-image
          - .env
          - evt
          - code/main.go
          - template.yml
          - .s
      CAPort: 9000
      Handler: main.handler
      MemorySize: 512
      Runtime: custom
```

上述项目可使用 `s init custom-golang -p alibaba` 来初始化，在这个项目下执行 `s invoke docker` 本地调试时会出现如下报错：

![image](https://user-images.githubusercontent.com/52195264/101321908-1cdbf780-38a1-11eb-98b5-6a735e2096a8.png)

## 建议

调试后发现是 fc 组件的 `s invoke docker` 部分在引用 `CodeUri` 时未考虑到 `Src` 的情况，因此出现路径错误。
